/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-21 07:17:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.example.event_booking_project_90.model.Review;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.example.event_booking_project_90.model.Review");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Photographer Reviews | Find Your Perfect Match</title>\n");
      out.write("    <!-- Google Fonts -->\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("    <!-- Tailwind CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary: #2c3e50;\n");
      out.write("            --secondary: #f39c12;\n");
      out.write("            --accent: #e74c3c;\n");
      out.write("            --light: #ecf0f1;\n");
      out.write("            --dark: #2c3e50;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("            color: var(--dark);\n");
      out.write("            overflow-x: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-section {\n");
      out.write("            background: linear-gradient(135deg, #2c3e50 0%, #1a252f 100%);\n");
      out.write("            height: 80vh;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-overlay {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            background: rgba(0, 0, 0, 0.4);\n");
      out.write("            z-index: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-content {\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 2;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-slider {\n");
      out.write("            background: white;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\n");
      out.write("            border-radius: 16px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            padding: 20px;\n");
      out.write("            transform: translateY(-80px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-card {\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-card:hover {\n");
      out.write("            transform: translateY(-10px);\n");
      out.write("            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-image {\n");
      out.write("            width: 220px;\n");
      out.write("            height: 220px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            object-fit: cover;\n");
      out.write("            border: 4px solid var(--secondary);\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-image:hover {\n");
      out.write("            transform: scale(1.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: var(--secondary);\n");
      out.write("            color: white;\n");
      out.write("            padding: 12px 24px;\n");
      out.write("            border-radius: 30px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: var(--accent);\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background-color: transparent;\n");
      out.write("            color: var(--secondary);\n");
      out.write("            border: 2px solid var(--secondary);\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 30px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background-color: var(--secondary);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .review-form {\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.05);\n");
      out.write("            padding: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-input {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 12px;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-input:focus {\n");
      out.write("            border-color: var(--secondary);\n");
      out.write("            box-shadow: 0 0 0 3px rgba(243, 156, 18, 0.2);\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .star-rating input {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .star-rating label {\n");
      out.write("            color: #ddd;\n");
      out.write("            font-size: 2rem;\n");
      out.write("            padding: 0 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .star-rating input:checked ~ label,\n");
      out.write("        .star-rating label:hover,\n");
      out.write("        .star-rating label:hover ~ label {\n");
      out.write("            color: var(--secondary);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .review-card {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 20px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.05);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .review-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .review-rating {\n");
      out.write("            color: var(--secondary);\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination-btn {\n");
      out.write("            background-color: var(--primary);\n");
      out.write("            color: white;\n");
      out.write("            width: 50px;\n");
      out.write("            height: 50px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination-btn:hover {\n");
      out.write("            background-color: var(--secondary);\n");
      out.write("            transform: scale(1.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .highlight {\n");
      out.write("            background: linear-gradient(120deg, rgba(243, 156, 18, 0.2) 0%, rgba(243, 156, 18, 0.2) 100%);\n");
      out.write("            background-repeat: no-repeat;\n");
      out.write("            background-size: 100% 40%;\n");
      out.write("            background-position: 0 90%;\n");
      out.write("            padding: 0 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo {\n");
      out.write("            font-weight: 700;\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            color: var(--secondary);\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-link {\n");
      out.write("            color: white;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-link:after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            width: 0;\n");
      out.write("            height: 2px;\n");
      out.write("            bottom: -5px;\n");
      out.write("            left: 0;\n");
      out.write("            background-color: var(--secondary);\n");
      out.write("            transition: width 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-link:hover:after {\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .testimonial-section {\n");
      out.write("            background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);\n");
      out.write("            padding: 80px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-title {\n");
      out.write("            position: relative;\n");
      out.write("            margin-bottom: 50px;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-title:after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            width: 80px;\n");
      out.write("            height: 4px;\n");
      out.write("            background-color: var(--secondary);\n");
      out.write("            bottom: -15px;\n");
      out.write("            left: 50%;\n");
      out.write("            transform: translateX(-50%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        footer {\n");
      out.write("            background-color: var(--primary);\n");
      out.write("            color: white;\n");
      out.write("            padding: 60px 0 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .social-links a {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            width: 40px;\n");
      out.write("            height: 40px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            background-color: rgba(255, 255, 255, 0.1);\n");
      out.write("            color: white;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            margin-right: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .social-links a:hover {\n");
      out.write("            background-color: var(--secondary);\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .footer-link {\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .footer-link:hover {\n");
      out.write("            color: var(--secondary);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        let profiles = [\n");
      out.write("            { name: \"Kamal\", role: \"Professional Photographer\", bio: \"Specializing in wedding photography with 8+ years of experience\", image: \"p11.jpg\" },\n");
      out.write("            { name: \"Sunil\", role: \"Portrait Photographer\", bio: \"Creating stunning portraits that capture the essence of you\", image: \"p22.jpg\" },\n");
      out.write("            { name: \"Amal\", role: \"Event Photographer\", bio: \"Documenting your special events with a creative touch\", image: \"p33.jpg\" },\n");
      out.write("            { name: \"Saman\", role: \"Commercial Photographer\", bio: \"Helping businesses tell their story through professional imagery\", image: \"p4.jpg\" },\n");
      out.write("            { name: \"Gihan\", role: \"Cinematographer\", bio: \"Crafting cinematic stories that bring your vision to life\", image: \"p5.jpg\" },\n");
      out.write("            { name: \"Sehan\", role: \"Videographer\", bio: \"Passionate about creating authentic and emotive films\", image: \"p6.jpg\" }\n");
      out.write("        ];\n");
      out.write("\n");
      out.write("        let currentIndex = 0;\n");
      out.write("\n");
      out.write("        function updateProfile() {\n");
      out.write("            let profile = profiles[currentIndex];\n");
      out.write("            document.getElementById(\"profile-image\").src = profile.image;\n");
      out.write("            document.getElementById(\"profile-name\").innerText = profile.name;\n");
      out.write("            document.getElementById(\"profile-role\").innerText = profile.role;\n");
      out.write("            document.getElementById(\"profile-bio\").innerText = profile.bio;\n");
      out.write("\n");
      out.write("            // Update the hidden field for the review form\n");
      out.write("            document.getElementById(\"selectedProfile\").value = profile.name;\n");
      out.write("            document.getElementById(\"currentProfileName\").innerText = profile.name;\n");
      out.write("\n");
      out.write("            // Update progress indicators\n");
      out.write("            document.querySelectorAll('.progress-indicator').forEach((indicator, index) => {\n");
      out.write("                if (index === currentIndex) {\n");
      out.write("                    indicator.classList.remove('bg-gray-300');\n");
      out.write("                    indicator.classList.add('bg-yellow-500');\n");
      out.write("                } else {\n");
      out.write("                    indicator.classList.remove('bg-yellow-500');\n");
      out.write("                    indicator.classList.add('bg-gray-300');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function nextProfile() {\n");
      out.write("            currentIndex = (currentIndex + 1) % profiles.length;\n");
      out.write("            updateProfile();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function prevProfile() {\n");
      out.write("            currentIndex = (currentIndex - 1 + profiles.length) % profiles.length;\n");
      out.write("            updateProfile();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function loadReviews() {\n");
      out.write("            let profileName = profiles[currentIndex].name;\n");
      out.write("            window.location.href = \"ReviewServlet?selectedProfile=\" + encodeURIComponent(profileName) + \"&redirect=past_reviews.jsp\";\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function setupStarRating() {\n");
      out.write("            const stars = document.querySelectorAll('.star-rating input');\n");
      out.write("            stars.forEach(star => {\n");
      out.write("                star.addEventListener('change', function() {\n");
      out.write("                    document.getElementById('rating').value = this.value;\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        window.onload = function() {\n");
      out.write("            updateProfile();\n");
      out.write("            setupStarRating();\n");
      out.write("        };\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Header/Navigation -->\n");
      out.write("    <header class=\"bg-gray-900 text-white py-4\">\n");
      out.write("        <div class=\"container mx-auto px-6 flex items-center justify-between\">\n");
      out.write("            <a href=\"#\" class=\"logo flex items-center\">\n");
      out.write("                <i class=\"fas fa-camera-retro mr-2\"></i>\n");
      out.write("                <span>SnapPro</span>\n");
      out.write("            </a>\n");
      out.write("            <nav class=\"hidden md:flex space-x-8\">\n");
      out.write("                <a href=\"#\" class=\"nav-link\">Home</a>\n");
      out.write("                <a href=\"#photographers\" class=\"nav-link\">Photographers</a>\n");
      out.write("                <a href=\"#reviews\" class=\"nav-link\">Reviews</a>\n");
      out.write("                <a href=\"#contact\" class=\"nav-link\">Contact</a>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"flex items-center\">\n");
      out.write("                <a href=\"SortedProfilesServlet\" class=\"btn-secondary hidden md:block\">Top Photographers</a>\n");
      out.write("                <button class=\"block md:hidden focus:outline-none\">\n");
      out.write("                    <i class=\"fas fa-bars text-white text-2xl\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <!-- Hero Section -->\n");
      out.write("    <section class=\"hero-section flex items-center\">\n");
      out.write("        <div class=\"hero-overlay\"></div>\n");
      out.write("        <div class=\"container mx-auto px-6 hero-content text-center text-white\">\n");
      out.write("            <h1 class=\"text-4xl md:text-6xl font-bold mb-6\">Find Your Perfect <span class=\"text-yellow-400\">Photographer</span></h1>\n");
      out.write("            <p class=\"text-lg md:text-xl mb-8 max-w-3xl mx-auto\">Discover talented photographers and videographers who can capture your special moments with style and creativity.</p>\n");
      out.write("            <a href=\"#photographers\" class=\"btn-primary inline-block\">Explore Photographers</a>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Photographer Profiles Section -->\n");
      out.write("    <section id=\"photographers\" class=\"py-20\">\n");
      out.write("        <div class=\"container mx-auto px-6\">\n");
      out.write("            <div class=\"profile-slider\">\n");
      out.write("                <div class=\"flex flex-col md:flex-row items-center\">\n");
      out.write("                    <!-- Profile Details -->\n");
      out.write("                    <div class=\"md:w-1/2 flex flex-col items-center text-center md:text-left md:items-start p-6\">\n");
      out.write("                        <h2 class=\"text-3xl font-bold mb-2\" id=\"profile-name\"></h2>\n");
      out.write("                        <p class=\"text-yellow-500 font-semibold mb-4\" id=\"profile-role\"></p>\n");
      out.write("                        <p class=\"text-gray-600 mb-6\" id=\"profile-bio\"></p>\n");
      out.write("                        <div class=\"flex space-x-4 mb-8\">\n");
      out.write("                            <button onclick=\"loadReviews()\" class=\"btn-secondary flex items-center\">\n");
      out.write("                                <i class=\"fas fa-star mr-2\"></i> View Reviews\n");
      out.write("                            </button>\n");
      out.write("                            <a href=\"#reviews\" class=\"btn-primary flex items-center\">\n");
      out.write("                                <i class=\"fas fa-pen-alt mr-2\"></i> Write Review\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- Social Media Links -->\n");
      out.write("                        <div class=\"flex space-x-4 mb-6\">\n");
      out.write("                            <a href=\"#\" class=\"text-gray-400 hover:text-yellow-500 transition-colors\">\n");
      out.write("                                <i class=\"fab fa-instagram text-xl\"></i>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"#\" class=\"text-gray-400 hover:text-yellow-500 transition-colors\">\n");
      out.write("                                <i class=\"fab fa-facebook text-xl\"></i>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"#\" class=\"text-gray-400 hover:text-yellow-500 transition-colors\">\n");
      out.write("                                <i class=\"fab fa-twitter text-xl\"></i>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"#\" class=\"text-gray-400 hover:text-yellow-500 transition-colors\">\n");
      out.write("                                <i class=\"fas fa-globe text-xl\"></i>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- Progress Indicators -->\n");
      out.write("                        <div class=\"flex space-x-2 mt-4\">\n");
      out.write("                            ");
 for(int i = 0; i < 6; i++) { 
      out.write("\n");
      out.write("                                <div class=\"progress-indicator w-8 h-2 rounded-full bg-gray-300 transition-colors\"></div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Profile Image -->\n");
      out.write("                    <div class=\"md:w-1/2 relative flex justify-center p-6\">\n");
      out.write("                        <div class=\"relative\">\n");
      out.write("                            <img id=\"profile-image\" src=\"\" alt=\"Photographer\" class=\"profile-image\">\n");
      out.write("                            <div class=\"absolute left-0 top-1/2 -translate-y-1/2 -translate-x-full\">\n");
      out.write("                                <button onclick=\"prevProfile()\" class=\"pagination-btn\">\n");
      out.write("                                    <i class=\"fas fa-chevron-left\"></i>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"absolute right-0 top-1/2 -translate-y-1/2 translate-x-full\">\n");
      out.write("                                <button onclick=\"nextProfile()\" class=\"pagination-btn\">\n");
      out.write("                                    <i class=\"fas fa-chevron-right\"></i>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Reviews Section -->\n");
      out.write("    <section id=\"reviews\" class=\"py-20 bg-gray-50\">\n");
      out.write("        <div class=\"container mx-auto px-6\">\n");
      out.write("            <h2 class=\"section-title text-3xl font-bold text-center mb-16\">Share Your Experience</h2>\n");
      out.write("\n");
      out.write("            <div class=\"grid grid-cols-1 lg:grid-cols-2 gap-10\">\n");
      out.write("                <!-- Review Form -->\n");
      out.write("                <div class=\"review-form\">\n");
      out.write("                    <h3 class=\"text-2xl font-bold mb-6\">Write a Review for <span id=\"currentProfileName\"></span></h3>\n");
      out.write("                    <form action=\"ReviewServlet\" method=\"post\" class=\"space-y-6\">\n");
      out.write("                        <input type=\"hidden\" name=\"selectedProfile\" id=\"selectedProfile\">\n");
      out.write("                        <input type=\"hidden\" name=\"rating\" id=\"rating\" value=\"5\">\n");
      out.write("\n");
      out.write("                        <div>\n");
      out.write("                            <label for=\"username\" class=\"block text-gray-700 font-medium mb-2\">Your Name</label>\n");
      out.write("                            <input type=\"text\" id=\"username\" name=\"username\" class=\"form-input\" required>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div>\n");
      out.write("                            <label class=\"block text-gray-700 font-medium mb-2\">Your Rating</label>\n");
      out.write("                            <div class=\"star-rating flex justify-center md:justify-start\">\n");
      out.write("                                <input type=\"radio\" id=\"star5\" name=\"star-rating\" value=\"5\" checked>\n");
      out.write("                                <label for=\"star5\"><i class=\"fas fa-star\"></i></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4\" name=\"star-rating\" value=\"4\">\n");
      out.write("                                <label for=\"star4\"><i class=\"fas fa-star\"></i></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3\" name=\"star-rating\" value=\"3\">\n");
      out.write("                                <label for=\"star3\"><i class=\"fas fa-star\"></i></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2\" name=\"star-rating\" value=\"2\">\n");
      out.write("                                <label for=\"star2\"><i class=\"fas fa-star\"></i></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1\" name=\"star-rating\" value=\"1\">\n");
      out.write("                                <label for=\"star1\"><i class=\"fas fa-star\"></i></label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div>\n");
      out.write("                            <label for=\"comment\" class=\"block text-gray-700 font-medium mb-2\">Your Experience</label>\n");
      out.write("                            <textarea id=\"comment\" name=\"comment\" rows=\"5\" class=\"form-input\" required placeholder=\"Share your experience working with this photographer...\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <button type=\"submit\" class=\"btn-primary w-full\">\n");
      out.write("                            <i class=\"fas fa-paper-plane mr-2\"></i>Submit Review\n");
      out.write("                        </button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Recent Reviews -->\n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"text-2xl font-bold mb-6\">Recent Reviews</h3>\n");
      out.write("\n");
      out.write("                    ");
 List<Review> reviews = (List<Review>) request.getAttribute("reviews");
                        if (reviews != null && !reviews.isEmpty()) {
                            for (Review review : reviews) { 
      out.write("\n");
      out.write("                    <div class=\"review-card\">\n");
      out.write("                        <div class=\"flex justify-between items-start mb-3\">\n");
      out.write("                            <div>\n");
      out.write("                                <h4 class=\"font-bold text-lg\">");
      out.print( review.getUsername() );
      out.write("</h4>\n");
      out.write("                                <div class=\"review-rating\">\n");
      out.write("                                    ");
 for(int i = 1; i <= 5; i++) { 
      out.write("\n");
      out.write("                                        <i class=\"");
      out.print( i <= review.getRating() ? "fas" : "far" );
      out.write(" fa-star\"></i>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"text-gray-500 text-sm\">2 days ago</div>\n");
      out.write("                        </div>\n");
      out.write("                        <p class=\"text-gray-600\">\"");
      out.print( review.getComment() );
      out.write("\"</p>\n");
      out.write("                    </div>\n");
      out.write("                    ");
 }
                        } else { 
      out.write("\n");
      out.write("                    <div class=\"review-card flex flex-col items-center justify-center py-10 text-center\">\n");
      out.write("                        <i class=\"far fa-comment-dots text-5xl text-gray-300 mb-4\"></i>\n");
      out.write("                        <p class=\"text-gray-500 mb-4\">No reviews yet. Be the first to review!</p>\n");
      out.write("                        <a href=\"#reviews\" class=\"btn-secondary\">Write a Review</a>\n");
      out.write("                    </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"mt-6 text-center\">\n");
      out.write("                        <a href=\"SortedProfilesServlet\" class=\"btn-primary inline-flex items-center\">\n");
      out.write("                            <i class=\"fas fa-award mr-2\"></i>\n");
      out.write("                            View Top Rated Photographers\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Testimonial Section -->\n");
      out.write("    <section class=\"testimonial-section\">\n");
      out.write("        <div class=\"container mx-auto px-6\">\n");
      out.write("            <h2 class=\"section-title text-3xl font-bold text-center\">What Our Clients Say</h2>\n");
      out.write("\n");
      out.write("            <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8 mt-16\">\n");
      out.write("                <div class=\"review-card text-center\">\n");
      out.write("                    <div class=\"w-20 h-20 rounded-full bg-gray-300 mx-auto mb-4 overflow-hidden\">\n");
      out.write("                        <img src=\"https://randomuser.me/api/portraits/women/32.jpg\" alt=\"Client\" class=\"w-full h-full object-cover\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4 class=\"font-bold text-lg mb-2\">Sarah Johnson</h4>\n");
      out.write("                    <div class=\"review-rating mb-4 justify-center flex\">\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <p class=\"text-gray-600\">\"Working with Kamal for our wedding was the best decision we made. The photos captured every moment perfectly!\"</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"review-card text-center\">\n");
      out.write("                    <div class=\"w-20 h-20 rounded-full bg-gray-300 mx-auto mb-4 overflow-hidden\">\n");
      out.write("                        <img src=\"https://randomuser.me/api/portraits/men/47.jpg\" alt=\"Client\" class=\"w-full h-full object-cover\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4 class=\"font-bold text-lg mb-2\">Michael Thomson</h4>\n");
      out.write("                    <div class=\"review-rating mb-4 justify-center flex\">\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star-half-alt\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <p class=\"text-gray-600\">\"Sunil did an amazing job with our corporate event photography. Professional, prompt and high-quality work.\"</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"review-card text-center\">\n");
      out.write("                    <div class=\"w-20 h-20 rounded-full bg-gray-300 mx-auto mb-4 overflow-hidden\">\n");
      out.write("                        <img src=\"https://randomuser.me/api/portraits/women/65.jpg\" alt=\"Client\" class=\"w-full h-full object-cover\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4 class=\"font-bold text-lg mb-2\">Emily Rodriguez</h4>\n");
      out.write("                    <div class=\"review-rating mb-4 justify-center flex\">\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <p class=\"text-gray-600\">\"Gihan created the most beautiful video of our wedding day. The storytelling and editing were absolutely perfect!\"</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Call to Action -->\n");
      out.write("    <section id=\"contact\" class=\"bg-yellow-500 py-20\">\n");
      out.write("        <div class=\"container mx-auto px-6 text-center\">\n");
      out.write("            <h2 class=\"text-3xl font-bold text-white mb-6\">Ready to Capture Your Special Moments?</h2>\n");
      out.write("            <p class=\"text-white text-lg mb-8 max-w-2xl mx-auto\">Connect with our talented photographers and videographers today to discuss your project needs.</p>\n");
      out.write("            <a href=\"#photographers\" class=\"bg-white text-yellow-500 font-bold py-3 px-8 rounded-full hover:bg-gray-100 transition-colors inline-flex items-center\">\n");
      out.write("                <i class=\"fas fa-search mr-2\"></i>\n");
      out.write("                Find Your Photographer\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer>\n");
      out.write("        <div class=\"container mx-auto px-6\">\n");
      out.write("            <div class=\"grid grid-cols-1 md:grid-cols-4 gap-8 mb-16\">\n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"text-xl font-bold mb-6\">SnapPro</h3>\n");
      out.write("                    <p class=\"text-gray-400 mb-6\">Connecting talented photographers with clients looking for exceptional visual content.</p>\n");
      out.write("                    <div class=\"social-links\">\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div>\n");
      out.write("                    <h4 class=\"text-lg font-bold mb-6\">Quick Links</h4>\n");
      out.write("                    <ul class=\"space-y-3\">\n");
      out.write("                        <li><a href=\"#\" class=\"footer-link\">Home</a></li>\n");
      out.write("                        <li><a href=\"#photographers\" class=\"footer-link\">Photographers</a></li>\n");
      out.write("                        <li><a href=\"#reviews\" class=\"footer-link\">Reviews</a></li>\n");
      out.write("                        <li><a href=\"SortedProfilesServlet\" class=\"footer-link\">Top Photographers</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div>\n");
      out.write("                    <h4 class=\"text-lg font-bold mb-6\">Resources</h4>\n");
      out.write("                    <ul class=\"space-y-3\">\n");
      out.write("                        <li><a href=\"#\" class=\"footer-link\">Photography Tips</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"footer-link\">Photography Styles</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"footer-link\">FAQ</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"footer-link\">Support</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div>\n");
      out.write("                    <h4 class=\"text-lg font-bold mb-6\">Contact Us</h4>\n");
      out.write("                    <ul class=\"space-y-3\">\n");
      out.write("                        <li class=\"flex items-start\">\n");
      out.write("                            <i class=\"fas fa-map-marker-alt mt-1 mr-3 text-yellow-500\"></i>\n");
      out.write("                            <span>123 Photography St, Colombo, Sri Lanka</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"flex items-center\">\n");
      out.write("                            <i class=\"fas fa-phone-alt mr-3 text-yellow-500\"></i>\n");
      out.write("                            <span>+94 123 456 789</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"flex items-center\">\n");
      out.write("                            <i class=\"fas fa-envelope mr-3 text-yellow-500\"></i>\n");
      out.write("                            <span>info@snappro.com</span>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"border-t border-gray-700 pt-8 text-center text-gray-400\">\n");
      out.write("                <p>© 2025 SnapPro. All rights reserved.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
